import { cn } from "@/lib/utils";
import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "./_components/Sidebar";
import AuthProvider from "./context/Authprovider";
export const dynamic = "force-dynamic";
const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "E-Commrce Store Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AuthProvider>

    <main className="flex">
      <Sidebar></Sidebar>
      <div
        className={cn(
          "min-h-full bg-background font-sans antialiased  ml-[20%] flex-1 px-8  mt-20",
          inter.variable
        )}
      >
        {children}
      </div>
    </main>
    </AuthProvider>

  );
}
