import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import Header from "@/app/(userInterface)/components/Header";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Mrrony Store ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen mx-3 !md:mx-0  md:container xl:px-28 bg-background font-sans antialiased ",
          inter.variable
        )}
      >
        <Header />
        <main className="">{children}</main>
      </body>
    </html>
  );
}
